### ISSUE TITLE
Question about the transformed datasets

### ISSUE THREAD

**Issue by linhh29** [lmb-freiburg/ovqa#2]
Hi! Congrats to your publication.

The transformation of vqa benchmark is interesting. But how can I get the transformed datasets after downloading original classification datasets (running which .py files)?

**Comment by simon-ging** [comment]
Hi, thanks for your interest.

I have added scripts to load only the datasets, they are in the root directory named `load_*.py`.

If you instead want to run the whole pipeline check the `run_scripts/` folder.

Hope this helps.

**Comment by simon-ging** [comment]
I will close this issue for now since I believe it is solved, feel free to reopen or create a new issue if you have further questions.
